### ISSUE TITLE
Exception Unhandled: System.NullReferenceException when playing Pokémon Ranger: Shadows of Almia sequences

### ISSUE THREAD

**Issue by PlatinumLucario** [Kermalis/NDSMusicStudio#11]
![image](https://user-images.githubusercontent.com/1906189/54973222-192c1280-4fe3-11e9-89bd-e4d2454dfeb3.png)
This unhandled exception occurs when playing sequences in Pokémon Ranger: Shadows of Almia, more specifically sequences such as SEQ_EVE_STAFFROLL

**Comment by Kermalis** [comment]
Just got this myself but in SongPlayer (same issue)
GBAMusicStudio also has this issue

**Comment by Kermalis** [comment]
This issue is now found at https://github.com/Kermalis/MusicStudio/issues/23
