### ISSUE TITLE
Pitch modulation is a bit off for some songs.

### ISSUE THREAD

**Issue by hi-note** [Kermalis/NDSMusicStudio#7]
Some songs that use modulation effects sound different on the console. Here's an example from Mario Kart DS. This is what it sounds like in the player for Waluigi Pinball https://cdn.discordapp.com/attachments/549787420606857226/551781456536403979/Waluigi_Pinball_wrong_modulation.mp3 and here's how it sounds like on the console https://www.youtube.com/watch?v=FT6PZUTdd04

**Comment by Kermalis** [comment]
Yeah, I'm unsure of the actual calculations that go on behind LFO and modulation, so I went with an educated guess. I'd have to devote some time to figuring that out

**Comment by Kermalis** [comment]
Closing for merge with GBA Music Studio
